Repository uprm-inso-4101-2020-2021-S1/semester-project-the-white-lotus, pull requests merged in 2020-09, with the labels that each got.

#1 Addition of the React project and skeleton of a README
  README.md
  rumbapr/.gitignore
  rumbapr/README.md
  rumbapr/package-lock.json
  rumbapr/package.json
  rumbapr/public/favicon.ico
  rumbapr/public/index.html
  rumbapr/public/logo192.png
  rumbapr/public/logo512.png
  rumbapr/public/manifest.json
  rumbapr/public/robots.txt
  rumbapr/src/App.css
  rumbapr/src/App.js
  rumbapr/src/App.test.js
  rumbapr/src/index.css
  rumbapr/src/index.js
  rumbapr/src/logo.svg
  rumbapr/src/serviceWorker.js
  rumbapr/src/setupTests.js
Labels: repo maintenance

#2 Changes to the README.md
  README.md
Labels: repo maintenance

#3 Changing in the wording of the README.md
  README.md
Labels: repo maintenance

#4 Added backend starter code
  server/.env.sample
  server/.eslintrc.js
  server/.gitignore
  server/LICENSE
  server/README.md
  server/package-lock.json
  server/package.json
  server/src/api/emojis.js
  server/src/api/index.js
  server/src/app.js
  server/src/index.js
  server/src/middlewares.js
  server/test/api.test.js
  server/test/app.test.js
Labels: general backend

#6 Addition of the navigation between pages and clean up of the repo
  A3 - Alondra Pereira.pdf
  rumbapr/package-lock.json
  rumbapr/package.json
  rumbapr/src/App.js
  rumbapr/src/pages/errorPage.js
  rumbapr/src/pages/forYouPage.js
  rumbapr/src/pages/landingPage.js
Labels: navigation

#7 Addition of the map to the landing page.
  rumbapr/package-lock.json
  rumbapr/package.json
  rumbapr/src/components/MapContainer.js
  rumbapr/src/pages/forYouPage.js
  rumbapr/src/pages/landingPage.js
Labels: maps

#8 Added database connection and routing
  rumbapr/.gitignore
  server/.env.sample
  server/models/Hosts.js
  server/models/Posts.js
  server/models/Users.js
  server/package-lock.json
  server/package.json
  server/src/api/posts.js
  server/src/api/users.js
  server/src/app.js
  server/src/db/posts.js
  server/src/index.js
  server/src/lib/posts.js
  server/src/routes.js
  server/src/utils.js
Labels: general backend

#12 Addition of the space for the header
  rumbapr/src/components/MapContainer.js
  rumbapr/src/pages/landingPage.css
  rumbapr/src/pages/landingPage.js
Labels: frontend

#16 There's a couple of commits as I changed everything
  .DS_Store
  rumbapr/package.json
  rumbapr/public/images/attractionLocation.png
  rumbapr/public/images/beachLocation.png
  rumbapr/public/images/beachLocation.psd
  rumbapr/public/images/foodLocation.png
  rumbapr/public/images/hotelLocation.png
  rumbapr/public/images/personLocation.png
  rumbapr/src/components/MapContainer.js
  rumbapr/src/dummy data/beaches.json
  rumbapr/src/pages/landingPage.css
  rumbapr/src/pages/landingPage.js
Labels: maps
